#    Numpy basics

In [7]:
import numpy as np
a = np.array([1,2,3,4,5])
b = [1,2,3,4,5]
print(a,b)
print(type(a),type(b))

[1 2 3 4 5] [1, 2, 3, 4, 5]
<class 'numpy.ndarray'> <class 'list'>


In [8]:
a = np.array((1,2,3,4,5))
print(a,type(a))

[1 2 3 4 5] <class 'numpy.ndarray'>


# 0 Dimension

In [9]:
a = np.array(9)
print(a)
print(a.ndim)

9
0


# 1 Dimension

In [10]:
a = np.array([1,2,3,4,5])
print(a)
print(a.ndim)

[1 2 3 4 5]
1


# 2 Dimensions

In [12]:
a = np.array([[1,2,3],[4,5,6]]) #([[],[]]) Syntax representing dim
print(a)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
2


# 3 Dimensions 

In [15]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(a)
print(a.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
3


In [20]:
l1 = [4,5,6,7,8,9]
l1

[4, 5, 6, 7, 8, 9]

In [25]:
arr = np.array(l1)
arr

array([4, 5, 6, 7, 8, 9])

### Converting array to list

In [21]:
arr.tolist()

[4, 5, 6, 7, 8, 9]

### Multiplying all the elements in the list by 4

In [22]:
arr*4

array([16, 20, 24, 28, 32, 36])

### Multiplying all the elements in the list by 4 using default method

In [23]:
l2 = [x*4 for x in l1]
l2

[16, 20, 24, 28, 32, 36]

### Multiplying all the elements in the list by 4 using for loop method

In [24]:
l2 = []
for i in l1:
    l2.append(i*4)
l2

[16, 20, 24, 28, 32, 36]

In [27]:
l2 = [1,2,3,4,5]
l = [l1,l2]
print(l)

[[4, 5, 6, 7, 8, 9], [1, 2, 3, 4, 5]]
