#    Numpy basics

## Modules
1. Importing Numpy Library 
2. Dimensions
3. Converting array to list 
4. Multiplying list using various method
5. Matrices
6. Matrix Multiplication
7. Using Random variables and probabilistic functions

## 1. Importing Library

In [55]:
import numpy as np
from numpy import random

In [44]:
a = np.array([1,2,3,4,5])
b = [1,2,3,4,5]
print(a,b)
print(type(a),type(b))

[1 2 3 4 5] [1, 2, 3, 4, 5]
<class 'numpy.ndarray'> <class 'list'>


In [8]:
a = np.array((1,2,3,4,5))
print(a,type(a))

[1 2 3 4 5] <class 'numpy.ndarray'>


## 2. Dimensions

### 0 Dimension

In [9]:
a = np.array(9)
print(a)
print(a.ndim)

9
0


### 1 Dimension

In [10]:
a = np.array([1,2,3,4,5])
print(a)
print(a.ndim)

[1 2 3 4 5]
1


### 2 Dimensions

In [12]:
a = np.array([[1,2,3],[4,5,6]]) #([[],[]]) Syntax representing dim
print(a)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
2


### 3 Dimensions 

In [15]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(a)
print(a.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
3


In [20]:
#list
l1 = [4,5,6,7,8,9]
l1

[4, 5, 6, 7, 8, 9]

In [25]:
#Array
arr = np.array(l1)
arr

array([4, 5, 6, 7, 8, 9])

## 3. Converting array to list

In [21]:
arr.tolist()

[4, 5, 6, 7, 8, 9]

## Multiplying each elements in the list by 4

### Multiplying all the elements in the list by 4

In [22]:
arr*4

array([16, 20, 24, 28, 32, 36])

### Multiplying all the elements in the list by 4 using default method

In [23]:
l2 = [x*4 for x in l1]
l2

[16, 20, 24, 28, 32, 36]

### Multiplying all the elements in the list by 4 using for loop method

In [24]:
l2 = []
for i in l1:
    l2.append(i*4)
l2

[16, 20, 24, 28, 32, 36]

In [28]:
l2 = [1,2,3,4,5]
l = [l1,l2]
print(l)

[[4, 5, 6, 7, 8, 9], [1, 2, 3, 4, 5]]


## 5. Matrices

In [30]:
l3 = [[1,2,3],[4,5,6],[7,8,9]]
arr1 = np.array(l3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
#Shape of the Matrix
arr1.shape 

(3, 3)

### Matrix Transpose

In [33]:
#Transpose Matrix
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## 6. Matrix Multiplication

In [34]:
#Matrix Multiplication
np.dot(arr1,arr1.T)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

## 7. Using Random variables and probabilistic functions

In [47]:
arr3 = np.random.randint(0,256,(3,28,28))
#np.random.randint(initial,last - 1,(matrices number, row rank, colloumn rank ))
arr3

array([[[ 33,   5, 157, ..., 120,  80, 158],
        [249, 174,  70, ..., 195, 207, 217],
        [ 29, 200, 182, ..., 205,  49,  86],
        ...,
        [208,  29, 172, ..., 210, 249,  61],
        [161,  96, 246, ..., 175, 156, 170],
        [158, 237, 148, ...,  54, 158, 130]],

       [[ 11,  98, 107, ..., 127, 175, 103],
        [109, 225,  67, ..., 240,  83,  21],
        [150, 173, 175, ..., 251, 104, 239],
        ...,
        [252,  72, 110, ...,  39,  22, 223],
        [109, 166,  30, ...,  10,  38,  57],
        [110, 132, 204, ...,  35, 116, 254]],

       [[139, 101, 120, ..., 196, 210, 227],
        [ 90, 220, 125, ..., 242,  36,  56],
        [115, 203,  23, ..., 223, 128, 247],
        ...,
        [253,  71,   0, ..., 234, 146,  91],
        [128,  26,  29, ..., 252, 168,   8],
        [189, 210, 187, ...,  45, 169, 130]]])

In [49]:
#locating the variable in array
arr3[0,0,0]

33

In [53]:
arr1

array([[[110,  87, 234],
        [124,  11, 136],
        [213, 252,  15]],

       [[ 63, 210, 156],
        [ 68, 105,  72],
        [163,  70, 168]]])

In [54]:
# locating the first row 
arr1[:,0]

array([[110,  87, 234],
       [ 63, 210, 156]])

In [58]:
#printing random Variables
x = random.randint(10, size=(10))
x

array([3, 4, 1, 5, 1, 5, 3, 1, 2, 2])

In [59]:
# printing root mean squre value 
print(np.var(x))

2.21


In [60]:
#printing standard deviation and average 
print(np.std(x))
print(np.average(x))

1.4866068747318506
2.7


In [61]:
# printing variables 
x = np.arange(0,10,1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
y = np.array([0,30,45,60,90])
r = np.deg2rad(y)
r

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [63]:
s = np.sin(r)
s

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])